[tool.poetry]
name = "poster"
version = "0.1.0"
description = ""
authors = ["Lukas Boehm <lukas.l.boehm@fau.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
